apiVersion: v1
kind: Service
metadata:
  name: employer-side-frontend-service
  labels:
    app: app
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http
    nodePort: 30080
  selector:
    app: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: employer-side-frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: employer-side-frontend
        image: us.gcr.io/glassy-outcome-200900/employer-side-frontend:{{ .Values.commit }}
        ports:
        - containerPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: employer-side-frontend-ingress-deployment
spec:
  rules:
    - host: 35.192.132.207/{{ .Release.Name }}
      http:
        paths:
          - backend:
              serviceName: employer-side-frontend-service
              servicePort: 80
            path: /
